on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
    - 'releases/**'
    paths:
      - 'setup.py'
    
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    # permissions:
    #  id-token: write 
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
        
    - name: Get previous tag
      id: previoustag
      uses: 'WyriHaximus/github-action-get-previous-tag@v1'
      with:
        fallback: 0.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get next minor version
      id: semver
      uses: 'WyriHaximus/github-action-next-semvers@v1'
      with:
        version: ${{ steps.previoustag.outputs.tag }}
    
    - name: Update PyPi version
      run: |
        sed -i 's/version=.*/version="${{ steps.semver.outputs.patch }}"/'  setup.py
    
    - name: Build source and wheel distributions
      run: |
        python -m pip install --upgrade build twine
        python -m build
        twine check --strict dist/*
    
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.semver.outputs.patch }}
        release_name: Release ${{ steps.semver.outputs.patch }}
